In [65]:
import numpy as np
import pandas as pd

In [66]:
column_names = ['nama', 'gender']
data = pd.read_csv('dataset_nama.csv',sep='@',names=column_names)

In [67]:
new_data = pd.read_csv('new name data.csv')
new_data.head()

name gender
0   Aathifah       F
1   Aathirah       F
2    Abadiah       F
3     Abella       F
4     Abidah       F

In [68]:
new_data.rename(columns={'name':'nama','M':'m'},inplace=True)

In [69]:
new_data.head()

nama gender
0   Aathifah       F
1   Aathirah       F
2    Abadiah       F
3     Abella       F
4     Abidah       F

In [70]:
data_gender = pd.concat([data,new_data])

In [71]:
data_gender.reset_index(inplace=True)

In [72]:
data_gender['gender'] = data_gender['gender'].str.lower()

In [73]:
data_gender.drop(columns='index', axis=1,inplace=True)

In [74]:
data_gender.head()

nama gender
0                 Agus  Suciono       m
1                 Andhien Ristu       f
2               Rani Dwi Astuti       f
3                  Rya Afriyati       f
4  Febrian Falentino Fredriktho       m

In [75]:
X=data_gender['nama']
y=data_gender['gender']

In [76]:
from sklearn.model_selection import train_test_split

In [77]:
from sklearn.feature_extraction.text import CountVectorizer

In [78]:
cv = CountVectorizer()

In [79]:
X = cv.fit_transform(X)

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

### Naive Bayes

In [81]:
from sklearn.naive_bayes import MultinomialNB

In [82]:
nb = MultinomialNB()

In [83]:
nb.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [84]:
predictions = nb.predict(X_test)

In [85]:
from sklearn.metrics import confusion_matrix,classification_report

In [86]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[2731   98]
 [ 361 1585]]


              precision    recall  f1-score   support

           f       0.88      0.97      0.92      2829
           m       0.94      0.81      0.87      1946

    accuracy                           0.90      4775
   macro avg       0.91      0.89      0.90      4775
weighted avg       0.91      0.90      0.90      4775



### logistic regression

In [87]:
from sklearn.linear_model import LogisticRegression

In [88]:
lg = LogisticRegression()

In [89]:
lg.fit(X_train,y_train)

C:\Users\Banna\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [90]:
lg_pred = lg.predict(X_test)

In [91]:
print(confusion_matrix(y_test,lg_pred))
print('\n')
print(classification_report(y_test,lg_pred))

[[2764   65]
 [ 608 1338]]


              precision    recall  f1-score   support

           f       0.82      0.98      0.89      2829
           m       0.95      0.69      0.80      1946

    accuracy                           0.86      4775
   macro avg       0.89      0.83      0.85      4775
weighted avg       0.87      0.86      0.85      4775



### Random forest

In [92]:
from sklearn.ensemble import RandomForestClassifier

In [93]:
rf = RandomForestClassifier(n_estimators=300)

In [94]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [95]:
rf_pred = rf.predict(X_test)

In [96]:
print(confusion_matrix(y_test,rf_pred))
print('\n')
print(classification_report(y_test,rf_pred))

[[2711  118]
 [ 635 1311]]


              precision    recall  f1-score   support

           f       0.81      0.96      0.88      2829
           m       0.92      0.67      0.78      1946

    accuracy                           0.84      4775
   macro avg       0.86      0.82      0.83      4775
weighted avg       0.85      0.84      0.84      4775



### Testing nama

In [97]:
def test_nama(nama):
    nama = [nama]
    nama = cv.transform(nama)
    return nb.predict(nama)

In [98]:
test_nama('Ahmad Al Banna')

array(['m'], dtype='<U1')